#!/usr/bin/with-contenv bash

# make our folders and links
mkdir -p /config/scripts
ln -s /config/scripts /scripts

# permissions
chown -R abc:abc /config

echo "User folders done"

if [ -f "/config/${CRONTAB_LIST_FILE}" ]; then \
  crontab /config/${CRONTAB_LIST_FILE}
else
  crontab /scripts/docker/crontab_list_ts.sh
fi
