#!/usr/bin/with-contenv bash

if [ -f "/scripts/index.js" ]; then \
  cd /scripts \
  && git pull
else
  git clone --depth=1 https://github.com/lxk0301/jd_scripts.git /scripts \
  && cd /scripts \
  && npm install
fi

echo "git done"

if [ -f "/config/${CRONTAB_LIST_FILE}" ]; then \
  crontab /config/${CRONTAB_LIST_FILE}
else
  crontab /scripts/docker/crontab_list_ts.sh
fi

crond

# make our folders and links
mkdir -p /config/scripts

ln -s /config/scripts /scripts

# permissions
chown -R abc:abc /config

echo "User folders done"
